[package]
name = "icicle-helper"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.0", features = ["derive"] }
uzers = "0.12"
libparted = "0.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
anyhow = "1.0"
distinst-disks = { git = "https://git.oss.uzinfocom.uz/xinux/distinst" }
distinst-disk-ops = { git = "https://git.oss.uzinfocom.uz/xinux/distinst" }
disk-types = { git = "https://git.oss.uzinfocom.uz/xinux/distinst" }

[[bin]]
name = "icicle-helper"
path = "src/main.rs"
